# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6c46e0d6ac2971f2da039dc2fee8db5b6493ca39d163c730d074537416f10307bf45a61aecd608d05b8e7915c6d9150824378aeaca115f8cbf230642b50c21a

test:
  secret_key_base: 0dfe3df7f281400b17abb5a5295cc41d274b29820051a0f59345e8d55fa4464cafa20a734a8f1b02200100bbbea57d184cb93e99b05e2c1087a6637047105482

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
